# Problem 29
# How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

def power_list(min_num, max_num)
    powers = []
    (min_num..max_num).each do |base|
        (min_num..max_num).each { |exponent| powers << (base ** exponent) }
    end
    distinct_powers(powers)
end

def distinct_powers(powers_list)
    puts "Answer: #{powers_list.uniq.sort.count} distinct terms"
end

power_list(2, 100)